### ISSUE TITLE
name link suggestion for [Bdellovibrio bacteriovorus]

### ISSUE THREAD

**Issue by Rajeshmbio** [globalbioticinteractions/globi-names#1]
Hi!
I found a taxon name ```Bdellovibrio bacteriovorus``` at a [globi page](http://www.globalbioticinteractions.org/?sourceTaxon=NCBI%3A264462&interactionType=preysOn). After reviewing the data sources and relevant taxonomic tools like the [globalnames resolver](http://resolver.globalnames.org), I think that suggestion below might be helpful.

 Thanks!

| name | suggested name | name url reference | notes
| --- | --- | --- | ---
| Bdellovibrio bacteriovorus | YOUR SUGGESTED NAME | http://somereference | some notes

**Comment by jhpoelen** [comment]
Hi @Rajeshmbio thanks for opening this issue regarding Bdellovibrio bacteriovorus . Is there a taxonomic name you'd like GloBI to link to, or would you like to suggest a name correction?

**Comment by jhpoelen** [comment]
@Rajeshmbio please re-open/comment you'd like to discuss this issue. Thanks!
